In [9]:
import numpy as np

In [10]:
my_list = [10,20,30,40]

In [11]:
type(my_list)

list

In [12]:
np.array(my_list)

array([10, 20, 30, 40])

In [13]:
my_numpy_array = np.array(my_list)

In [14]:
type(my_numpy_array)

numpy.ndarray

In [15]:
my_numpy_array.max()

40

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.random.random(5)

array([0.86153156, 0.39304809, 0.00748062, 0.24751032, 0.64872279])

In [19]:
# array arithmetic

In [20]:
my_list1 = [1,2]
my_list2 = [2,3]

In [21]:
my_list1+my_list2

[1, 2, 2, 3]

In [22]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)

In [23]:
my_numpy_array1+my_numpy_array2

array([3, 5])

In [24]:
my_numpy_array1*my_numpy_array2

array([2, 6])

In [25]:
my_numpy_array1-my_numpy_array2

array([-1, -1])

In [26]:
my_numpy_array1/my_numpy_array2

array([0.5       , 0.66666667])

In [27]:
my_numpy_array1*4

array([4, 8])

In [28]:
other_array = np.array([10,20,30,40,50])

In [29]:
other_array.min()

10

In [30]:
other_array.sum()

150

In [31]:
my_numpy_array1

array([1, 2])

In [32]:
# diziler üzerinde işlem yapılabilmesi için boyutlar ya aynı olmalı ya da ikisinden
# biri tek boyutlu olmalı
#my_numpy_array1+other_array

In [33]:
#arange & indexing

In [34]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
np_array = np.arange(0,10)

In [67]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np_array[-1]

9

In [71]:
np_array[1:4:]

array([1, 2, 3])

In [73]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [75]:
np_array[2:6:2]

array([2, 4])

In [77]:
# random

In [79]:
np.random.randn(4)

array([ 0.04488104,  0.15905001,  0.13398937, -0.35083308])

In [81]:
np.random.randn(4,4)

array([[-1.00455333,  1.53553914, -0.26999962, -0.69968459],
       [-1.62186555,  0.14917196, -0.13962824,  1.39875508],
       [ 0.92392256,  2.0319743 , -0.35194808, -0.70472411],
       [-0.67009905,  0.91859075,  1.48295864, -1.05925975]])

In [83]:
np.random.randint(1,300,5)

array([194, 285, 177, 288, 292])