In [1]:
import numpy as np

In [3]:
my_matrix = [[5,10],[15,20]]

In [5]:
my_matrix[0]

[5, 10]

In [7]:
my_matrix[0][1]

10

In [9]:
# row * column

In [13]:
numpy_matrix = np.array([[5,10],[10,20]])

In [15]:
numpy_matrix

array([[ 5, 10],
       [10, 20]])

In [19]:
numpy_matrix[1][1]

20

In [21]:
numpy_matrix.sum()

45

In [23]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.random.random((3,2))

array([[0.24440604, 0.7585412 ],
       [0.82260739, 0.08818007],
       [0.06512636, 0.6810856 ]])

In [31]:
# matrix arithmetic

In [33]:
first_array = np.array([[10,20],[30,40]])

In [37]:
second_array = np.array([[50,60],[70,80]])

In [39]:
first_array + second_array

array([[ 60,  80],
       [100, 120]])

In [41]:
first_array

array([[10, 20],
       [30, 40]])

In [43]:
third_array = np.array([[50,60]])

In [45]:
third_array

array([[50, 60]])

In [47]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [49]:
fourth_array = np.array([[10,20,30,40,50]])

In [57]:
# toplama işleminde boyutlar aynı olmalı
first_array + fourth_array

ValueError: operands could not be broadcast together with shapes (2,2) (1,5) 

In [59]:
third_array = np.array([[10],[20]])

In [61]:
third_array

array([[10],
       [20]])

In [65]:
third_array.shape

(2, 1)

In [67]:
first_array.shape

(2, 2)

In [69]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [71]:
# matrix multiplication

In [73]:
first_array

array([[10, 20],
       [30, 40]])

In [75]:
second_array

array([[50, 60],
       [70, 80]])

In [77]:
first_array * second_array

array([[ 500, 1200],
       [2100, 3200]])

In [79]:
# dot product

In [81]:
first_matrix = np.array([[10,20,30]])

In [83]:
first_matrix

array([[10, 20, 30]])

In [85]:
first_matrix.shape

(1, 3)

In [87]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [89]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [91]:
second_matrix.shape

(3, 2)

In [95]:
# first_matrix * second_matrix
#hata verir

In [103]:
result_matrix = first_matrix.dot(second_matrix)

In [105]:
result_matrix

array([[120, 180]])

In [107]:
result_matrix.shape

(1, 2)