In [1]:
import numpy as np

In [3]:
new_array = np.random.randint(1,100,20)

In [5]:
new_array

array([63,  1, 74, 41, 65, 41, 71, 67, 31, 85, 20, 58, 14, 66, 56, 76, 22,
       90, 54, 83])

In [7]:
new_array > 25

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True])

In [9]:
new_array[new_array>25]

array([63, 74, 41, 65, 41, 71, 67, 31, 85, 58, 66, 56, 76, 90, 54, 83])

In [11]:
# transpose & reshape

In [13]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [15]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [19]:
# row ve column yerleri değiştirilir
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [21]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [23]:
random_array = np.random.random((6,1))

In [25]:
random_array

array([[0.19037933],
       [0.27380101],
       [0.44810099],
       [0.29292623],
       [0.41629729],
       [0.52766064]])

In [27]:
random_array.shape

(6, 1)

In [29]:
random_array.reshape(2,3)

array([[0.19037933, 0.27380101, 0.44810099],
       [0.29292623, 0.41629729, 0.52766064]])

In [31]:
random_array.reshape(3,2)

array([[0.19037933, 0.27380101],
       [0.44810099, 0.29292623],
       [0.41629729, 0.52766064]])

In [33]:
random_array

array([[0.19037933],
       [0.27380101],
       [0.44810099],
       [0.29292623],
       [0.41629729],
       [0.52766064]])

In [35]:
# z-score

In [37]:
data = np.array([10,12,13,15,18,25,100,105])

In [39]:
#outlier

In [41]:
mean = np.mean(data)

In [43]:
mean

37.25

In [55]:
data.sum() / len(data)

37.25

In [57]:
std=np.std(data)

In [59]:
std

37.9333296719389

In [61]:
z_scores = (data - mean)/std

In [63]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [65]:
z_scores[z_scores>1]

array([1.65421809, 1.78602829])

In [67]:
data[z_scores>1]

array([100, 105])

In [69]:
#math equations

In [71]:
# 2x + 3y = 8 and 5x + 7y = 19

In [73]:
#coefficient

In [75]:
A = np.array([[2,3],[5,7]])

In [77]:
#constant

In [79]:
b = np.array([8,19])

In [81]:
solution = np.linalg.solve(A,b)

In [83]:
solution

array([1., 2.])