In [3]:
#!pip install torch torchvision

In [5]:
import torch # derin ağdaki katman yapımından sorumlu
import numpy as np

In [7]:
# pytorch datatypes - tensors

In [9]:
torch.tensor(10)

tensor(10)

In [11]:
torch.tensor([10,20])

tensor([10, 20])

In [13]:
scalar = torch.tensor(10)

In [15]:
type(scalar)

torch.Tensor

In [17]:
scalar

tensor(10)

In [19]:
scalar +5 

tensor(15)

In [21]:
scalar.dim()

0

In [23]:
scalar.shape

torch.Size([])

In [25]:
scalar.item()

10

In [27]:
type(scalar.item())

int

In [31]:
numpy_int = np.int32(10)

In [33]:
numpy_int

10

In [35]:
numpy_int + 10

20

In [37]:
scalar_from_np = torch.tensor(numpy_int)

In [39]:
scalar_from_np

tensor(10, dtype=torch.int32)

In [45]:
scalar_from_np.dtype

torch.int32

In [47]:
scalar.dtype

torch.int64

In [49]:
new_scalar = torch.tensor(25,dtype=torch.int32)

In [51]:
new_scalar

tensor(25, dtype=torch.int32)

In [53]:
new_scalar + 10

tensor(35, dtype=torch.int32)

In [57]:
tensor_float = torch.tensor(3.14)

In [59]:
tensor_float

tensor(3.1400)

In [61]:
tensor_float.dtype

torch.float32

In [63]:
# vectors

In [65]:
vector = torch.tensor([2,3])

In [67]:
vector.dim()

1

In [69]:
vector.shape

torch.Size([2])

In [71]:
vector = torch.tensor([1,2,3])

In [73]:
vector.dim()

1

In [75]:
vector.shape

torch.Size([3])

In [77]:
# count # of [] -> dimension
# count elements -> shape

In [79]:
matrix = torch.tensor([[1,2],[3,4]])

In [81]:
matrix

tensor([[1, 2],
        [3, 4]])

In [83]:
matrix.dim()

2

In [85]:
matrix.shape

torch.Size([2, 2])

In [97]:
tensor_example = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [99]:
tensor_example.dim()

3

In [101]:
tensor_example.shape

torch.Size([1, 3, 3])

In [103]:
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [105]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                              device=None, #cpu,gpu
                              requires_grad=False #öğrenme sürecine dahil olup olmaması
                              )

In [107]:
float_32_tensor

tensor([3., 6., 9.])

In [109]:
float_32_tensor.dtype

torch.float32