In [1]:
import torch
import numpy as np

In [3]:
random_array = np.random.randn(3,5)
# 3 sıra 5 kolon

In [4]:
random_array

array([[ 0.25876771,  0.27728558,  0.66313102,  3.32520108, -2.01485478],
       [-0.87782513,  1.291096  , -1.07250289, -1.25581358, -0.9218001 ],
       [-0.82291854,  1.44185777, -0.63543876,  1.0506468 , -0.3717069 ]])

In [5]:
type(random_array)

numpy.ndarray

In [9]:
random_array.shape

(3, 5)

In [11]:
random_array.ndim

2

In [13]:
random_matrix = torch.rand(size=(3,5))

In [15]:
random_matrix

tensor([[0.6184, 0.5492, 0.6975, 0.0292, 0.8255],
        [0.8177, 0.7520, 0.2609, 0.8867, 0.6616],
        [0.9684, 0.8458, 0.1698, 0.7032, 0.9636]])

In [17]:
random_matrix.ndim

2

In [19]:
random_matrix.shape

torch.Size([3, 5])

In [21]:
random_matrix.dtype

torch.float32

In [23]:
random_image_tensor = torch.rand(size=(224,224,3))

In [25]:
random_image_tensor

tensor([[[0.8909, 0.7782, 0.3109],
         [0.7966, 0.6901, 0.9665],
         [0.0703, 0.0375, 0.5828],
         ...,
         [0.1695, 0.4520, 0.0922],
         [0.5306, 0.5580, 0.1620],
         [0.8420, 0.0659, 0.4037]],

        [[0.4801, 0.9938, 0.7446],
         [0.5649, 0.3978, 0.5857],
         [0.2149, 0.8510, 0.8562],
         ...,
         [0.9040, 0.8110, 0.7951],
         [0.8779, 0.1801, 0.0460],
         [0.0485, 0.7965, 0.1697]],

        [[0.2023, 0.4395, 0.0564],
         [0.9704, 0.6567, 0.7790],
         [0.5241, 0.9104, 0.8665],
         ...,
         [0.2130, 0.2398, 0.7593],
         [0.6973, 0.1161, 0.6137],
         [0.9842, 0.1100, 0.6887]],

        ...,

        [[0.8348, 0.3280, 0.6452],
         [0.8566, 0.8130, 0.2832],
         [0.7224, 0.9557, 0.1464],
         ...,
         [0.6411, 0.4675, 0.4893],
         [0.7348, 0.9529, 0.1504],
         [0.8181, 0.9314, 0.0968]],

        [[0.2658, 0.1049, 0.2409],
         [0.0406, 0.8582, 0.9055],
         [0.

In [27]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [29]:
random_image_tensor.ndim

3

In [31]:
zeros = torch.zeros(size=(3,2))

In [33]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [37]:
ones = torch.ones(size=(3,2))

In [39]:
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [45]:
vector_with_arange = torch.arange(start=0,end=10,step=1)

In [47]:
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [51]:
similar_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
x_tensor = torch.tensor([1,2,3])

In [55]:
x_tensor

tensor([1, 2, 3])

In [59]:
x_tensor + 15

tensor([16, 17, 18])

In [61]:
x_tensor * 31.14

tensor([31.1400, 62.2800, 93.4200])

In [63]:
x_tensor = x_tensor + 10

In [65]:
x_tensor

tensor([11, 12, 13])

In [67]:
x_tensor.subtract(1000)

tensor([-989, -988, -987])

In [69]:
x_tensor.multiply(-1)

tensor([-11, -12, -13])

In [71]:
x_tensor.divide(-1)

tensor([-11., -12., -13.])

In [73]:
x_tensor * x_tensor

tensor([121, 144, 169])

In [75]:
y_tensor = torch.tensor([4,5])

In [77]:
x_tensor

tensor([11, 12, 13])

In [79]:
y_tensor

tensor([4, 5])

In [81]:
x_tensor * y_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0