In [1]:
import torch
import numpy as np

In [3]:
tensor = torch.tensor([1,2,3])

In [5]:
tensor * tensor

tensor([1, 4, 9])

In [7]:
matrix = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [9]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [11]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [13]:
matrix , matrix

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [17]:
torch.matmul(matrix,matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [19]:
matrix.shape

torch.Size([3, 3])

In [21]:
tensor1 = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

In [23]:
tensor2 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])

In [25]:
tensor1.shape

torch.Size([3, 2])

In [27]:
tensor2.shape

torch.Size([3, 2])

In [29]:
tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [35]:
tensor2 = tensor2.T

In [37]:
tensor1 @ tensor2

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [39]:
A = torch.tensor([[1,2,3]])

In [41]:
A.shape

torch.Size([1, 3])

In [43]:
A.ndim

2

In [45]:
B = torch.tensor([[4],[5],[6]])

In [47]:
B.shape

torch.Size([3, 1])

In [49]:
B.ndim

2

In [55]:
result = A @ B

In [57]:
result

tensor([[32]])

In [59]:
result.shape

torch.Size([1, 1])

In [61]:
result.ndim

2