In [47]:
import torch

In [48]:
tensor = torch.arange(0,50,5)

In [49]:
tensor.min()

tensor(0)

In [50]:
tensor.max()

tensor(45)

In [51]:
tensor.sum()

tensor(225)

In [52]:
tensor.median()

tensor(20)

In [53]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [68]:
tensor.dtype

torch.int64

In [70]:
tensor = tensor.type(torch.float)

In [72]:
tensor.mean()

tensor(22.5000)

In [74]:
#argmax, argmin

In [76]:
tensor.max()

tensor(45.)

In [78]:
tensor.argmax()

tensor(9)

In [80]:
tensor[9]

tensor(45.)

In [82]:
tensor[1][0]

IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

In [84]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [86]:
matrix.shape

torch.Size([2, 3])

In [88]:
matrix.ndim

2

In [90]:
matrix[1][1]

tensor(5)

In [92]:
#manipulating tensor: reshaping, stacking, squeezing, unsqueezing

In [94]:
x = torch.arange(1,10,1)

In [96]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
x.shape

torch.Size([9])

In [100]:
x.ndim

1

In [102]:
x = torch.tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
x_reshaped = x.reshape(1,9)

In [108]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [110]:
x_reshaped.shape

torch.Size([1, 9])

In [112]:
x_reshaped.ndim

2

In [116]:
y = torch.randn(224,224,3)

In [118]:
y.shape

torch.Size([224, 224, 3])

In [120]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [122]:
x_reshaped = x.reshape(3,3)

In [124]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [126]:
x_reshaped = x.reshape(9,1)

In [128]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [130]:
#view

In [132]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [134]:
x_reshaped[0]=20

In [136]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [138]:
x

tensor([[20,  2,  3,  4,  5,  6,  7,  8,  9]])

In [140]:
x_view = x.view(9,1)

In [142]:
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [144]:
x_view[0]=10

In [146]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [148]:
x

tensor([[10,  2,  3,  4,  5,  6,  7,  8,  9]])

In [150]:
# view -> contigioua tensor

In [152]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

In [156]:
x.is_contiguous()

True

In [158]:
y = x.T

In [162]:
y.is_contiguous()

False

In [164]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [166]:
y.view(1,6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [168]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [170]:
# stacking

In [172]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [174]:
torch.stack([x,x,x,x],dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [176]:
torch.stack([x,x,x,x],dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [178]:
# squeeze & unsqueeze

In [180]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [182]:
x.shape

torch.Size([2, 3])

In [184]:
x.ndim

2

In [186]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [188]:
x.squeeze().shape

torch.Size([2, 3])

In [190]:
x = torch.tensor([[1,2,3]])

In [192]:
x.ndim

2

In [194]:
x.shape

torch.Size([1, 3])

In [196]:
x.squeeze()

tensor([1, 2, 3])

In [198]:
x

tensor([[1, 2, 3]])

In [200]:
x.squeeze().ndim

1

In [202]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [204]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [206]:
x.unsqueeze(dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [208]:
y = x.unsqueeze(dim=0)

In [210]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [212]:
y.ndim

3

In [214]:
y.shape

torch.Size([1, 2, 3])

In [216]:
z = y.unsqueeze(dim=0)

In [218]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [220]:
z.ndim

4

In [222]:
z.shape

torch.Size([1, 1, 2, 3])

In [224]:
t = z.squeeze()

In [226]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [228]:
t.ndim

2

In [230]:
# permute

In [232]:
x = torch.rand(size=(224,224,3))

In [234]:
x.shape

torch.Size([224, 224, 3])

In [238]:
x_permuted = x.permute(2,0,1) # axis 0 -> 1, 1-> 2, 2-> 0

In [240]:
x_permuted.shape

torch.Size([3, 224, 224])

In [242]:
# indexing & slicing

In [250]:
a = torch.arange(1,10,1)

In [252]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
a = a.reshape(1,3,3)

In [256]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [258]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [260]:
a[0][0][0]

tensor(1)

In [266]:
a.shape

torch.Size([1, 3, 3])

In [264]:
a[:,0,0]

tensor([1])

In [268]:
a[:,1,0]

tensor([4])

In [270]:
a[:,2,1]

tensor([8])

In [274]:
a[:,:,0] # first column

tensor([[1, 4, 7]])

In [276]:
# random seed

In [292]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])