In [1]:
import torch

In [3]:
torch.cuda.is_available()

False

In [5]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.enabled)

2.5.1
None
True


In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [9]:
device

'cpu'

In [11]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

In [13]:
device

'cpu'

In [15]:
tensor = torch.tensor([1,2,3])

In [17]:
tensor

tensor([1, 2, 3])

In [19]:
tensor.device

device(type='cpu')

In [21]:
# manual

In [23]:
tensor_on_gpu = tensor.to(device)

In [25]:
tensor_on_gpu

tensor([1, 2, 3])

In [27]:
tensor.numpy()

array([1, 2, 3], dtype=int64)

In [29]:
tensor_on_gpu.numpy()

array([1, 2, 3], dtype=int64)

In [33]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3], dtype=int64)

In [35]:
# context manager

In [37]:
with torch.device(device):
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20,30)

In [39]:
tensor2.device

device(type='cpu')

In [43]:
layer.weight.device

device(type='cpu')

In [45]:
# torch.set_default_device

In [47]:
device

'cpu'

In [49]:
torch.set_default_device(device)

In [51]:
tensor4 = torch.tensor([1,2,3])

In [53]:
layer2 = torch.nn.Linear(10,20)

In [55]:
tensor4.device

device(type='cpu')